### ISSUE TITLE
Where can we add our social media contact buttons?

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/factastichealth_website#14]
to our 
twitter: https://twitter.com/FactasticHealth
facebook: https://www.facebook.com/factastichealth/
instagram: https://www.instagram.com/factastichealth/

**Comment by fauno** [comment]
Hi! What do you think of putting them on the menu, between About and Search?

**Comment by selimerunkut** [comment]
If you think it will look good their? or under the search (and line)

![Uploading Screenshot 2021-03-17 at 20.19.55.png…]()

**Comment by fauno** [comment]
I think it will be difficult to make them float exactly there, what I was thinking is moving Blog and About to the left to make space for the icons, so Blog, About, Facebook, Twitter, Etc, Search bar are on the same line

**Comment by selimerunkut** [comment]
sure 👍
