### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/factastichealth_website#3]
Add Google Analytics

**Comment by fauno** [comment]
I'll need the GA code for this one :)

**Comment by overqint** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-110579843-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-110579843-1');
</script>
