### ISSUE TITLE
Text & Images are missing

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/factastichealth_website#8]
Text is missing here:
the-cause-of-autoimmune-diseases-are-unknown-part-2

original post: https://factastichealth.com/the-cause-of-autoimmune-diseases-are-unknown-part-2

Images are missing:
the-cause-of-autoimmune-diseases-are-unknown-part-6

original post: https://factastichealth.com/the-cause-of-autoimmune-diseases-are-unknown-part-6

**Comment by selimerunkut** [comment]
@fauno we will check the posts 1 by 1 and comment further about differences if we find any

**Comment by fauno** [comment]
Hi, is the previous site still up somewhere so I can check?

**Comment by fauno** [comment]
This is the post contents according to the backup.  It's the same as the migrated, only that the HTML to Markdown conversion removed the newlines, I'll check what happened.

```html
<h2>What about the Leaky Gut?</h2>
The food choices we make can damage our gut directly with their physical or chemical properties if they are for example: acidic, greasy, digestive-intensive like meat or poor in nutrients.

Indirectly the above-mentioned kind of foods imbalance the microbiome, the most important residents in our gut, billions and billions of microorganisms that live in the mucus layer of our intestines. They form one part of our gut functional barrier.

Physicians ignoring the <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5682732/">effect of our diet and how that relates to inflammatory rheumatoid diseases like arthritis or ankylosing spondylitis</a> is very short-sighted and leads to symptom management rather than dealing with the cause of the disease.

Through scientific research, it is known that in most people with inflamed, leaky gut conditions, protein fragments from foods and gut organisms enter the bloodstream after most meals.
Our immune system forms antibodies in response to these foreign bodies and components of milk, wheat or egg proteins for example. The antibodies are formed within a very short time (hours) after consuming these foods.

In <a href="https://factastichealth.com/the-cause-of-autoimmune-diseases-are-unknown-part-3">Part 3</a> we will get into foods that are the culprits of a leaky gut.
```

**Comment by selimerunkut** [comment]
Website is online here: https://factastichealth.com/ (reverted the DNS changes, so it would be accessible again)

**Comment by selimerunkut** [comment]
Text under the photos needs to have another format

<img width="491" alt="Screenshot 2021-03-13 at 10 53 44" src="https://user-images.githubusercontent.com/31136147/111026539-fe7b2000-83ea-11eb-9f42-94ed5305c29e.png">

**Comment by fauno** [comment]
Hi, for the text under the picture, there's a special markdown syntax you need to follow, I'll put an example on the README. I see you were modifying articles, was that in relation to this issue?

**Comment by selimerunkut** [comment]
Thanks, that would be great;
the modifying was to change some content.
