### ISSUE TITLE
The images of the post overview pages are all different sizes

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/factastichealth_website#9]
The images of the posts overview are all different sizes and the overall design looks misaligned, how can we solve this issue, some examples:

<img width="1253" alt="Screenshot 2021-03-14 at 00 58 08" src="https://user-images.githubusercontent.com/31136147/111052995-70da1780-8460-11eb-8287-da2c3f8f9ddb.png">
<img width="1236" alt="Screenshot 2021-03-14 at 00 57 09" src="https://user-images.githubusercontent.com/31136147/111052996-75063500-8460-11eb-9248-57b2f63031bf.png">

**Comment by fauno** [comment]
This is done too :)
